<?php

namespace AppBundle\Repository;

/**
 * BestelstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestelstatusRepository extends \Doctrine\ORM\EntityRepository
{
}
